- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
Ajout des templates issue feature request et bug.
closes #1
> Ajout des templates issue feature request et bug

- .github/MERGE_REQUEST_TEMPLATE/pul_request_template.md
Il s'agit d'un template qui permettra d'avoir de demander toutes les informations importantes concernant la pull request.
closes #3
> Ajout du template de pull request

- code_of_conduct.md
Ce document définit les règles de conduite à respecter par les collaborateurs à ce projet
closes #11
> Ajout du code of conduct

- contributing.md
Ce fichier sert à fournir des directives et des informations aux contributeurs potentiels sur la manière de contribuer de manière efficace et appropriée au projet open source.
closes #9
> Ajout du contributing

- .gitignore
- index.php
- package-lock.json
- package.json
- public/index.php
Ce commit consiste à rajouter un menu des différentes recettes disponible sur le site internet. L'utilisateur trouvera ces recettes sur le menu dynamique du site.
closes #16
> Ajout d'un menu de recette sur la page d'accueil

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
Correction de la partie "assignee"
closes #18
> Correction des templates

- database/connection.php
- database/migration.php
Création des fichiers de connexion et migration de la base de données
closes #20
> Mise en place de la connexion à la base de donnée

- public/register.php
Cette page permet aux utilisateurs de s'inscrire
closes #23
> Ajout de la page d'inscription

- public/connexion.php
Ajout d'une page de connexion
Ajout d'une page de connexion
closes #22
> page de connexion

- public/recettes.js
La page a été crée et permettra aux abonnées d'avoir les informations souhaités dans l'issue.
closes #28
> Page d'affichage des recettes et des commentaires

- public/register.php
- public/subscribe.php
La page d'abonnement offre de plusieurs abonnements
- Free (par défaut)
- Basic 
- Premium 
closes #25
> Page d'offre d'abonnement

- public/connexion.php
- public/menu.js
Les bugs du menu ont été corrigés 
closes #26
> Correction des bugs du menu 

- public/profil.js
- public/profil.php
Les utilisateurs pourront dès à présent avoir une page de profil
closes #24
> Ajout d'une page de profil

- public/community.js
- public/register.php
- public/subscribe.php
Une page communauté sur un site de recettes culinaires permet aux utilisateurs de partager, commenter et découvrir de nouvelles recettes. Les avantages incluent le partage d'expériences, la possibilité de poser des questions, et la création d'une communauté engagée
closes #27
> Page communauté

- public/assets/js/recettes.js
La partie commentaire est fonctionnelle.
closes #45
> Correction du bug de la partie commentaire

- .gitignore
- public/failles/sql.php
- public/failles/xss.js
Empêcher que des utilisateurs puissent injecter du code dans les formulaires ou récupérer des informations de notre base de données
[]- Est-ce que cela a entraîné une augmentation de la version sémantique ?
Oui, c'est une correction d'anomalie 
closes #32
> Correction des failles XSS et d'injection SQL

- public/index.php
Permettre aux utilsateurs de rechercher plus facilement sur le site
closes #29
> Mise en place d'un barre de recherche avec JQuery

- public/assets/js/favoris.js
Les utilisateurs peuvent desormais avoir des recettes favorites.
Les utilisateurs peuvent desormais avoir des recettes favorites.
closes #30
> Ajout d'une partie favoris

- public/assets/js/favoris.js
- public/assets/js/notification.js
- public/assets/js/tutorial.js
> tutoriel video

- public/assets/js/mail.js
Les utlisateurs vont desormais recevoir une notification.
closes #35
> Notification par Mail

- public/send.php
Maintenant les utilisateurs pourront partager le ou les contenus qui souhaitent.
closes #34
> Mise en place du partage

- .gitignore
- api_spoonacular/.gitignore
- api_spoonacular/.htaccess
- api_spoonacular/README.md
- api_spoonacular/database/connection.php
- api_spoonacular/entities/members/create-member.php
- api_spoonacular/entities/members/delete-member.php
- api_spoonacular/entities/members/get-members.php
- api_spoonacular/entities/members/is-member-logged-in.php
- api_spoonacular/entities/members/login-member.php
- api_spoonacular/entities/members/logout-member.php
- api_spoonacular/entities/members/register-member.php
- api_spoonacular/entities/members/update-member.php
- api_spoonacular/index.php
- api_spoonacular/libraries/body.php
- api_spoonacular/libraries/header.php
- api_spoonacular/libraries/method.php
- api_spoonacular/libraries/parameters.php
- api_spoonacular/libraries/path.php
- api_spoonacular/libraries/response.php
- api_spoonacular/migrations/migration.php
- api_spoonacular/routes/authentification/login.php
- api_spoonacular/routes/authentification/logout.php
- api_spoonacular/routes/authentification/register.php
- api_spoonacular/routes/members/delete.php
- api_spoonacular/routes/members/get.php
- api_spoonacular/routes/members/patch.php
- api_spoonacular/routes/members/post.php
- api_spoonacular/routes/not-found/all.php
- public/send.php
[]- Est-ce que cela a entraîné une augmentation de la version sémantique ?
Oui, nous passons à la version 2.0.0
> Mise en prod de l'api

- .eslintrc.js
- .eslintrc.yml
- package.json
- public/send.php
Les utilisateurs verront leur code js analysé lors du commit afin de verifier les erreurs
closes #63
> Mise en place de la vérification js
